-- Banks master table for seller bank dropdown
CREATE TABLE IF NOT EXISTS `banks` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_banks_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `banks` (`name`) VALUES
('Allahabad Bank'),
('Andhra Bank'),
('Axis Bank'),
('Bandhan Bank'),
('Bank of Baroda'),
('Bank of India'),
('Bank of Maharashtra'),
('Canara Bank'),
('Catholic Syrian Bank'),
('Central Bank of India'),
('City Union Bank'),
('Corporation Bank'),
('DCB Bank'),
('Dena Bank'),
('Dhanlaxmi Bank'),
('Federal Bank'),
('HDFC Bank'),
('HSBC Bank India'),
('ICICI Bank'),
('IDBI Bank'),
('IDFC FIRST Bank'),
('Indian Bank'),
('Indian Overseas Bank'),
('IndusInd Bank'),
('Jammu & Kashmir Bank'),
('Karnataka Bank'),
('Karur Vysya Bank'),
('Kotak Mahindra Bank'),
('Lakshmi Vilas Bank'),
('Nainital Bank'),
('Punjab and Sind Bank'),
('Punjab National Bank'),
('RBL Bank'),
('South Indian Bank'),
('Standard Chartered Bank India'),
('State Bank of India'),
('Syndicate Bank'),
('Tamilnad Mercantile Bank'),
('UCO Bank'),
('Union Bank of India'),
('United Bank of India'),
('Vijaya Bank'),
('Yes Bank'),
('AU Small Finance Bank'),
('Equitas Small Finance Bank'),
('ESAF Small Finance Bank'),
('Fincare Small Finance Bank'),
('Jana Small Finance Bank'),
('Suryoday Small Finance Bank'),
('Ujjivan Small Finance Bank'),
('Utkarsh Small Finance Bank'),
('Airtel Payments Bank'),
('India Post Payments Bank'),
('Paytm Payments Bank'),
('NSDL Payments Bank'),
('Fino Payments Bank'),
('Apna Sahakari Bank'),
('Bassein Catholic Co-operative Bank'),
('Bharat Co-operative Bank'),
('Bombay Mercantile Co-operative Bank'),
('Cosmos Co-operative Bank'),
('Janata Sahakari Bank'),
('Kalupur Commercial Co-operative Bank'),
('Mehsana Urban Co-operative Bank'),
('NKGSB Co-operative Bank'),
('Saraswat Co-operative Bank'),
('Shamrao Vithal Co-operative Bank'),
('The Gujarat State Co-operative Bank'),
('Thane Bharat Sahakari Bank'),
('Abhyudaya Co-operative Bank'),
('Rajkot Nagarik Sahakari Bank'),
('TJSB Sahakari Bank'),
('Dombivli Nagari Sahakari Bank'),
('Kallappanna Awade Ichalkaranji Janata Sahakari Bank'),
('Nutan Nagarik Sahakari Bank'),
('Sutex Co-operative Bank'),
('Suco Souharda Sahakari Bank'),
('Bharatiya Mahila Bank'),
('Deutsche Bank India'),
('DBS Bank India'),
('MUFG Bank India'),
('Mizuho Bank India'),
('BNP Paribas India'),
('Credit Agricole CIB India'),
('Bank of America India'),
('Citi Bank India'),
('JPMorgan Chase Bank India'),
('Barclays Bank India'),
('Royal Bank of Scotland India'),
('Doha Bank India'),
('Qatar National Bank India'),
('Mashreq Bank India'),
('Emirates NBD India'),
('Societe Generale India'),
('Sumitomo Mitsui Banking Corporation India'),
('First Abu Dhabi Bank India'),
('Woori Bank India'),
('Shinhan Bank India'),
('KEB Hana Bank India'),
('Industrial Bank of Korea India')
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);