-- Create table and seed Indian states, districts, and major cities for cascading dropdowns
CREATE TABLE IF NOT EXISTS `indian_locations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `state_name` VARCHAR(120) NOT NULL,
  `district_name` VARCHAR(120) NOT NULL,
  `city_name` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_state_district_city` (`state_name`,`district_name`,`city_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `indian_locations` (`state_name`, `district_name`, `city_name`) VALUES
('Andhra Pradesh','Anantapur','Anantapur'),
('Andhra Pradesh','Chittoor','Tirupati'),
('Andhra Pradesh','Krishna','Vijayawada'),
('Andhra Pradesh','Visakhapatnam','Visakhapatnam'),
('Arunachal Pradesh','Papum Pare','Itanagar'),
('Arunachal Pradesh','West Siang','Aalo'),
('Assam','Kamrup Metropolitan','Guwahati'),
('Assam','Dibrugarh','Dibrugarh'),
('Assam','Silchar','Silchar'),
('Bihar','Patna','Patna'),
('Bihar','Gaya','Gaya'),
('Bihar','Muzaffarpur','Muzaffarpur'),
('Chhattisgarh','Raipur','Raipur'),
('Chhattisgarh','Bilaspur','Bilaspur'),
('Chhattisgarh','Durg','Bhilai'),
('Delhi','Central Delhi','New Delhi'),
('Delhi','North West Delhi','Rohini'),
('Delhi','South Delhi','Saket'),
('Goa','North Goa','Panaji'),
('Goa','South Goa','Margao'),
('Gujarat','Ahmedabad','Ahmedabad'),
('Gujarat','Surat','Surat'),
('Gujarat','Vadodara','Vadodara'),
('Gujarat','Rajkot','Rajkot'),
('Haryana','Gurugram','Gurugram'),
('Haryana','Faridabad','Faridabad'),
('Haryana','Panchkula','Panchkula'),
('Himachal Pradesh','Shimla','Shimla'),
('Himachal Pradesh','Kangra','Dharamshala'),
('Himachal Pradesh','Kullu','Kullu'),
('Jammu and Kashmir','Srinagar','Srinagar'),
('Jammu and Kashmir','Jammu','Jammu'),
('Jharkhand','Ranchi','Ranchi'),
('Jharkhand','Dhanbad','Dhanbad'),
('Jharkhand','East Singhbhum','Jamshedpur'),
('Karnataka','Bengaluru Urban','Bengaluru'),
('Karnataka','Mysuru','Mysuru'),
('Karnataka','Dharwad','Hubballi'),
('Karnataka','Dakshina Kannada','Mangaluru'),
('Kerala','Thiruvananthapuram','Thiruvananthapuram'),
('Kerala','Ernakulam','Kochi'),
('Kerala','Kozhikode','Kozhikode'),
('Madhya Pradesh','Bhopal','Bhopal'),
('Madhya Pradesh','Indore','Indore'),
('Madhya Pradesh','Jabalpur','Jabalpur'),
('Maharashtra','Mumbai','Mumbai'),
('Maharashtra','Pune','Pune'),
('Maharashtra','Nagpur','Nagpur'),
('Maharashtra','Nashik','Nashik'),
('Manipur','Imphal West','Imphal'),
('Meghalaya','East Khasi Hills','Shillong'),
('Mizoram','Aizawl','Aizawl'),
('Nagaland','Kohima','Kohima'),
('Odisha','Khordha','Bhubaneswar'),
('Odisha','Cuttack','Cuttack'),
('Odisha','Sambalpur','Sambalpur'),
('Punjab','Ludhiana','Ludhiana'),
('Punjab','Amritsar','Amritsar'),
('Punjab','Jalandhar','Jalandhar'),
('Rajasthan','Jaipur','Jaipur'),
('Rajasthan','Jodhpur','Jodhpur'),
('Rajasthan','Kota','Kota'),
('Rajasthan','Udaipur','Udaipur'),
('Sikkim','East Sikkim','Gangtok'),
('Tamil Nadu','Chennai','Chennai'),
('Tamil Nadu','Coimbatore','Coimbatore'),
('Tamil Nadu','Madurai','Madurai'),
('Tamil Nadu','Tiruchirappalli','Tiruchirappalli'),
('Telangana','Hyderabad','Hyderabad'),
('Telangana','Warangal','Warangal'),
('Telangana','Ranga Reddy','Ranga Reddy'),
('Tripura','West Tripura','Agartala'),
('Uttar Pradesh','Lucknow','Lucknow'),
('Uttar Pradesh','Kanpur Nagar','Kanpur'),
('Uttar Pradesh','Varanasi','Varanasi'),
('Uttar Pradesh','Prayagraj','Prayagraj'),
('Uttarakhand','Dehradun','Dehradun'),
('Uttarakhand','Haridwar','Haridwar'),
('West Bengal','Kolkata','Kolkata'),
('West Bengal','Howrah','Howrah'),
('West Bengal','Darjeeling','Siliguri'),
('Andaman and Nicobar Islands','South Andaman','Port Blair'),
('Chandigarh','Chandigarh','Chandigarh'),
('Dadra and Nagar Haveli and Daman and Diu','Daman','Daman'),
('Ladakh','Leh','Leh'),
('Lakshadweep','Kavaratti','Kavaratti'),
('Puducherry','Puducherry','Puducherry');
